# Generated by Django 2.1.13 on 2021-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='home1',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='sunshine/images')),
            ],
        ),
        migrations.CreateModel(
            name='home2',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='', upload_to='sunshine/images')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
