# Generated by Django 2.1.13 on 2021-02-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunshine', '0002_auto_20210216_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home1',
            name='image',
            field=models.ImageField(upload_to='sunshine/images'),
        ),
    ]
